//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masters
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Experience { get; set; }
        public int IDGender { get; set; }
        public string Schedule { get; set; }
    
        public virtual Gender Gender { get; set; }
    }
}
